  language: python
  python:
    - "3.7"
  services:
    - mysql
  before_install:
    - mysql -e 'CREATE DATABASE fitbox2go_test;'
  install:
    - pip install pipenv
    - pipenv install
  script:
    - pytest --cov=src --cov-config .coveragerc
  after_success:
    - coveralls
