"""empty message

Revision ID: 2bff406e4f42
Revises: 5172760a5fae
Create Date: 2020-01-26 15:58:02.071092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bff406e4f42'
down_revision = '5172760a5fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_schedules', 'end_schedule_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_schedules', sa.Column('end_schedule_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
