"""empty message

Revision ID: 5172760a5fae
Revises: a9aa7e98c903
Create Date: 2020-01-24 10:34:08.032017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5172760a5fae'
down_revision = 'a9aa7e98c903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogposts')
    op.create_foreign_key(None, 'daily_schedules', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'exercises', 'daily_schedules', ['schedule_id'], ['schedule_id'])
    op.create_foreign_key(None, 'exercises', 'exercise_types', ['exercise_type_id'], ['exercise_type_id'])
    op.alter_column('fitboxes', 'current_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'fitboxes', 'users', ['current_user_id'], ['user_id'])
    op.create_foreign_key(None, 'medical_checks', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'patient_infos', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'results', 'result_types', ['result_type_id'], ['result_type_id'])
    op.create_foreign_key(None, 'results', 'trainings', ['training_id'], ['training_id'])
    op.create_foreign_key(None, 'trainings', 'exercises', ['exercise_id'], ['exercise_id'])
    op.create_foreign_key(None, 'users', 'users', ['supervisor_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'patient_infos', type_='foreignkey')
    op.drop_constraint(None, 'medical_checks', type_='foreignkey')
    op.drop_constraint(None, 'fitboxes', type_='foreignkey')
    op.alter_column('fitboxes', 'current_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_constraint(None, 'daily_schedules', type_='foreignkey')
    op.create_table('blogposts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contents', mysql.TEXT(), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
