"""empty message

Revision ID: c3ea5c78a026
Revises: 2bff406e4f42
Create Date: 2020-01-27 12:19:54.484950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ea5c78a026'
down_revision = '2bff406e4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'patient_infos', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_infos', type_='unique')
    # ### end Alembic commands ###
